// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StandoffPortfolioTracker.Infrastructure;

#nullable disable

namespace StandoffPortfolioTracker.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("StandoffPortfolioTracker.Core.Entities.AppliedAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InventoryItemId")
                        .HasColumnType("int");

                    b.Property<int>("SlotPosition")
                        .HasColumnType("int");

                    b.Property<int>("StickerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InventoryItemId");

                    b.HasIndex("StickerId");

                    b.ToTable("AppliedAttachments");
                });

            modelBuilder.Entity("StandoffPortfolioTracker.Core.Entities.GameCollection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("GameCollections");
                });

            modelBuilder.Entity("StandoffPortfolioTracker.Core.Entities.InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsStatTrack")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ItemBaseId")
                        .HasColumnType("int");

                    b.Property<int>("PortfolioAccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("PurchasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemBaseId");

                    b.HasIndex("PortfolioAccountId");

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("StandoffPortfolioTracker.Core.Entities.ItemBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CollectionId")
                        .HasColumnType("int");

                    b.Property<decimal>("CurrentMarketPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Rarity")
                        .HasColumnType("int");

                    b.Property<string>("SkinName")
                        .HasColumnType("longtext");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId");

                    b.ToTable("ItemBases");
                });

            modelBuilder.Entity("StandoffPortfolioTracker.Core.Entities.MarketHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemBaseId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ItemBaseId");

                    b.ToTable("MarketHistory");
                });

            modelBuilder.Entity("StandoffPortfolioTracker.Core.Entities.PortfolioAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("PortfolioAccounts");
                });

            modelBuilder.Entity("StandoffPortfolioTracker.Core.Entities.AppliedAttachment", b =>
                {
                    b.HasOne("StandoffPortfolioTracker.Core.Entities.InventoryItem", "InventoryItem")
                        .WithMany("Attachments")
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StandoffPortfolioTracker.Core.Entities.ItemBase", "Sticker")
                        .WithMany()
                        .HasForeignKey("StickerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryItem");

                    b.Navigation("Sticker");
                });

            modelBuilder.Entity("StandoffPortfolioTracker.Core.Entities.InventoryItem", b =>
                {
                    b.HasOne("StandoffPortfolioTracker.Core.Entities.ItemBase", "ItemBase")
                        .WithMany()
                        .HasForeignKey("ItemBaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StandoffPortfolioTracker.Core.Entities.PortfolioAccount", "PortfolioAccount")
                        .WithMany("Items")
                        .HasForeignKey("PortfolioAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemBase");

                    b.Navigation("PortfolioAccount");
                });

            modelBuilder.Entity("StandoffPortfolioTracker.Core.Entities.ItemBase", b =>
                {
                    b.HasOne("StandoffPortfolioTracker.Core.Entities.GameCollection", "Collection")
                        .WithMany()
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collection");
                });

            modelBuilder.Entity("StandoffPortfolioTracker.Core.Entities.MarketHistory", b =>
                {
                    b.HasOne("StandoffPortfolioTracker.Core.Entities.ItemBase", "ItemBase")
                        .WithMany()
                        .HasForeignKey("ItemBaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemBase");
                });

            modelBuilder.Entity("StandoffPortfolioTracker.Core.Entities.InventoryItem", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("StandoffPortfolioTracker.Core.Entities.PortfolioAccount", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
